### ISSUE TITLE
Smart contracts health badges

### ISSUE THREAD

**Issue by s0b0lev** [maddevsio/mythril-scanner#1]
Badges is a representation of smart contracts security health status.

Badges library: https://github.com/jongracecox/anybadge 

### TODO:
 - [ ] Place status text to rectangle: **Mythril-Scanner: passed|minors issues|critical issues**
 - [ ] Change color regarding badge status (badge status described bellow)

### Badge statuses:
1. **Green**  - no issues
2. **Yellow** - there are minor issues
3. **Red** - there are critical issues

### Badges API:
```
method: GET
endpoint: `/badge/github/<repo_owner>/<repo_name>`
```

### Badges usage
```
[Mythril Scanner Badge](http://methrylscan.com/badge/github/<repo_owner>/<repo_name>)
```

**Comment by s0b0lev** [comment]
Basic badges: success and fail added.
Should consider a way to store badges:
1. Pre-generate all possible badges
2. Generate badge via PIL on badge requests (not prefered way)

**Comment by Big-Bo99** [comment]
Found badge generator package: https://github.com/jongracecox/anybadge

**Comment by s0b0lev** [comment]
@Big-Bo99 looks cool, lets use it : )

**Comment by s0b0lev** [comment]
Badges was added.
